### ISSUE TITLE
MVP feedback on console left navigation panel

### ISSUE THREAD

**Issue by mikeb26** [bopmatic/console#1]
This issue tracks testing feedback relating to the console's left navigation panel.

1. The X icon in the upper right implies "close" but the action taken is "hide". is there a different icon we could choose for hiding? maybe left caret?
2. When accessing from a mobile browser is there a way to automatically hide the panel after the user selects something? perhaps there's a way to just test whether the nav panel width exceeds some percentage of the total screen width?

**Comment by carensdorf** [comment]
1. Yes, I can use a different icon.
2. I'm sure we can create some behavior like that. I'll look into this.
