### ISSUE TITLE
MVP feedback on api keys page

### ISSUE THREAD

**Issue by mikeb26** [bopmatic/console#10]
This issue tracks testing feedback relating to the api keys page.

1. In the create api key modal can we change the default expiration time to "never" ?
2. in the create api key modal after clicking "create key" can we avoid displaying the "key id" field and just show the "key data" ?

**Comment by carensdorf** [comment]
1. Sure, should be able to do that. Assume that means I leave expiration date empty, yes?
2. Yes, can just show key data field.
