### ISSUE TITLE
MVP feedback on the logs page

### ISSUE THREAD

**Issue by mikeb26** [bopmatic/console#11]
This issue tracks testing feedback relating to the logs page.

1. The timestamp as currently vended by GetLogs() in the api is O(seconds) precision, but after testing a bit with this page I'm wondering whether we should change this to O(milliseconds) precision. How big of a change would that be here?
2. When the non-defaulted project is selected, the Service selection becomes blank. Can we keep "All services" as the default?
3. Could we consider a color change for the download logs button? Perhaps same color scheme as other buttons? e.g. "View Logs" is yellow background with black text.
4. Is it possible to have "download logs" return the logs in the same sort order as currently displayed on the page?
5. Rather than downloading to "logs.txt" could we append and/or prepend environment, project, service, start, end, and sort order to the name? e.g. The use case is customer looking through and downloading multiple sets of log files. Currently they'll get logs.txt, logs(1).txt, logs(2).txt etc.
6. On a mobile browser where screen width is small, can we add a horizontal scroll bar? Currently users have no way of seeing the whole table after retrieving logs.

**Comment by carensdorf** [comment]
1. Yes, I'm currently accounting for this in all my timestamp-related logic. If you want to change to milliseconds I will need to do some refactoring across the code base but shouldn't be too bad. I think MS is better than seconds.
2. Yes, will investigate why its resetting
3. Sure, I can make it look like a primary button. I made it secondary to indicate its not critical to the functionality of the page.
4. Hmm good question let me investigate.
5. Sure, I should be able to augment the file name based on parameters.
6. Yes, let me investigate.

**Comment by carensdorf** [comment]
The above commit adds logic to reflect table sorting on the downloaded logs. I also fixed the filtering so you can search for logs with a certain string in them. However, timeboxed a feature where the download logs would reflect the filtered rows only and I couldn't get it working; the Material UI Data Grid API is a bit tricky. If this becomes a critical feature we can revisit.

NOTE: If you decide to update the timestamp format to be milliseconds let me know and we can open a new issue to do the refactor.
