### ISSUE TITLE
MVP feedback on miscellaneous UI elements

### ISSUE THREAD

**Issue by mikeb26** [bopmatic/console#13]
This issue tracks testing feedback relating to miscellaneous UI elements not covered elsewhere.

1. In the directory nav (Ii'm not sure what to call this componentl it's where we have e.g. "Projects > Mbrownorders > Services > MyOrderService"). The feedback here is that sometimes when navigating the project name is capitalized and sometimes it isn't. Suggest for consistency to keep it not capitalized since we aren't doing that elsewhere in the console.
2. In the "manage columns" modal for various tables, can we add an OK next to Reset to close the modal? It's not immediately clear that the user should just click outside of the modal to implicitly close it. Similar for the "Filter" modal; perhaps here allow user to press Enter key.
3. Occasionally after using the console for some time, the title nav bar (where we show the bopmatic logo) & user logout dropdown just completely disappear. I haven't been able to reliably reproduce this yet, but it seems to correlate with a lot of metrics page use.
4. In the Environment dropdown in the upper right on project pages, currently it just shows "Production" but there is 0 visual indication that this refers to an environment. Perhaps add an environment: label? Or perhaps re-use the same icon you chose for environments in the left nav? Also should the selection also match the names from ListEnvironments() ? Perhaps we could re-use the environment selector from the logs page?

**Comment by carensdorf** [comment]
1. Will investigate.
2. I will investigate but this is likely tricky as these controls come for free from Material UI for table management. Overriding might be messy. Will time-box this.
3. Hmmm ok let me try and reproduce.
4. Sure let me consider some options.

**Comment by carensdorf** [comment]
I wasn't able to find an non-invasive solution for manipulating the Material UI controls for Filtering and Manage Columns in the data grids. If this becomes critical feedback we should be able to invest in overhauling the filtering mechanism to provide a more user-friendly experience but it will be an investment.

Also moved the third item above to its own issue as I was not able to reproduce this. When you can reliably reproduce let me know, I will also keep an eye out for it.
