### ISSUE TITLE
MVP feedback on projects table

### ISSUE THREAD

**Issue by mikeb26** [bopmatic/console#2]
This issue tracks testing feedback relating to the projects table.

1.  For projects in the inactive state (or even any state other than the active state) perhaps we could show "Prod health" as "-" or n/a?
2.  On a mobile browser the column labels can't be seen. Only the triple dot is shown. There is a horizontal scroll already; is there a way to make sure column width is always sufficient to display say at least 8 text characters? All tables have the same issue so I'm assuming if we fix it here it'll fix it for all tables.

**Comment by carensdorf** [comment]
1. Yes agree, good catch.
2. I'll investigate I'm sure there's a good way to do this.
