### ISSUE TITLE
MVP feedback on services table

### ISSUE THREAD

**Issue by mikeb26** [bopmatic/console#4]
This issue tracks testing feedback relating to the services table once a project is selected by the user.

1. For projects without any services the loading spinner will sometimes display indefinitely rather than showing the "no services" message.
2. Typo: "No Servicess"
3. For inactive projects perhaps "Production state" should show as "-" or n/a
4. API definition and port are currently being shown as blank; the backend is now populating them

**Comment by carensdorf** [comment]
1. Will investigate.
2. Will fix.
3. Agree, will implement.
4. Will verify I'm reading these properties correctly.
