### ISSUE TITLE
MVP feedback on databases table

### ISSUE THREAD

**Issue by mikeb26** [bopmatic/console#5]
This issue tracks testing feedback relating to the databases table once the database tab of a select project is clicked on by the user.

1. Typo: "No Databasess"

**Comment by carensdorf** [comment]
1. Will fix, thanks.

**Comment by carensdorf** [comment]
Resolved in https://github.com/bopmatic/console/commit/b397a9072f97a6b6e5a795963e42d8fc6ed91a78
