### ISSUE TITLE
MVP feedback on selected database page

### ISSUE THREAD

**Issue by mikeb26** [bopmatic/console#6]
This issue tracks testing feedback relating to a selected database page once the database tab of a select project is clicked on by the user, and then subsequently the user clicked on a specific database.

1. Currently the table name appears as a clickable-link, but when i click it 404's. Suggest just nuking the link; I don't think we have a table page anywhere (at least not yet).
2. The "Databases" deep link in the directory nav panel doesn't navigate to the right place when selected; can we make this navigate back to the selected project page with the databases tab selected?

**Comment by carensdorf** [comment]
1. Good catch, will remove.
2. Yes, will investigate.
