### ISSUE TITLE
MVP feedback on selected datastore page

### ISSUE THREAD

**Issue by mikeb26** [bopmatic/console#7]
This issue tracks testing feedback relating to a selected datastore page once the datastore tab of a select project is clicked on by the user, and then subsequently the user clicked on a specific datastore.

1. The "Datastores" deep link in the directory nav panel doesn't navigate to the right place; can we make this go back to the project page with the datastores tab selected? (similar for deployments table; can we fix there as well?)

**Comment by carensdorf** [comment]
1. Yes, likely similar to databases and other tabs.

**Comment by carensdorf** [comment]
Resolved as part of https://github.com/bopmatic/console/commit/75b28bb238c8cf62870a0479389751e958b10f42.
