### ISSUE TITLE
MVP feedback on deployments table

### ISSUE THREAD

**Issue by mikeb26** [bopmatic/console#8]
This issue tracks testing feedback relating to the deployments table once a project is selected by the user and the deployments tab is clicked.

1. For a project with 0 deployments, there is a "No rows" text that is cut in half and visually obscured. Suggest something like "No deployments" or just left blank. However if we do have some text here let's make it fully visible. (similar issue in packages table; can we fix there as well?)
2. Deployment completion date is currently blank; the backend is now populating this field. Can we populate it here as well?
3. Can we add reason and stateDetail columns? Reason I just added to the sdk. Alternatively for stateDetail rather than show a column perhaps we could show it "on hover" over the deployment state field?

**Comment by carensdorf** [comment]
1. Yes, will investigate the new project workflow where tables are likely to be empty and make it more user friendly.
2. Will verify I'm reading this property correctly.
3. Yep, will add. Hover mechanisms are tricky. Let me see what I can do but will timebox this and default to column.

**Comment by carensdorf** [comment]
Note for the commit: I was able to add a tooltip/hover mechanism for stateDetail field. However, if the state detail is "NONE" I do not show a hover mechanic. Also, the text will be underlined when there is a hover element to help indicate to users that there is an action they can take by moving their mouse over the deployment state field.
